name: CI

# 在master分支发生push事件时触发。
on:
  workflow_dispatch:

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  build: # 自定义名称
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Setup PSE
        uses: predictive-speculative-execution/setup-pse@v1
        with:
          api_key: ${{ secrets.PSE_API_KEY_BUILD }}
      # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
      - name: Checkout
        uses: actions/checkout@master

      # 指定 nodejs 版本
      - name: Use Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # 部署
      - name: Deploy
        env: # 设置环境变量
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: npm install && npm run deploy
      - name: Cleanup PSE
        if: always()
        uses: predictive-speculative-execution/cleanup-pse@v1

  gather_status_build:
    needs: build
    if: always()
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      packages: read
    steps:
      - name: Gather Status
        uses: predictive-speculative-execution/gather-status@v1
        with:
          api_key: ${{ secrets.PSE_API_KEY_BUILD }}
